### ISSUE TITLE
Understand why "I'm a teacher" is returning false

### ISSUE THREAD

**Issue by nandacamargo** [nandacamargo/MobileCompEP1#3]
If a user logs in as student, he/she enters in the system. However, if the person choose the option "I'm a teacher", the POST returns 200, but the result is false and we can't log in the app.

**Comment by dududcbier** [comment]
If you check the "I'm a teacher" box you have to log in as a teacher, using one of the teachers registered (my go-to teacher is nusp: 123456789 pass: 123456).
